SELECT
  DISTINCT
  role.ROLE2_ID,
  role.ROLE_MODEL_ID,
  role.NAME
FROM dbo.ROLE2 role
  INNER JOIN dbo.ROLE_MODEL rm ON role.ROLE_MODEL_ID = rm.ROLE_MODEL_ID
  INNER JOIN dbo.LNK_ROLE_PERS_RES_AR l ON role.ROLE2_ID = l.ROLE2_ID
WHERE l.PERSONAGE_ID = ? AND l.RESOURCE_ID = ? AND rm.ACTIVE = 1