SELECT
  DISTINCT
  role.ROLE2_ID,
  role.ROLE_MODEL_ID,
  role.NAME
FROM ROLE2 role
  INNER JOIN ROLE_MODEL rm ON role.ROLE_MODEL_ID = rm.ROLE_MODEL_ID
  INNER JOIN V_PERSONAGE_ROLES2 vpr2 ON role.ROLE2_ID = vpr2.VALUE_ID
WHERE role.ROLE2_ID = ? AND vpr2.PARENT_ID = ? AND rm.ACTIVE = 1