SELECT
  DISTINCT
  role.ROLE2_ID,
  role.ROLE_MODEL_ID,
  role.NAME
FROM ROLE2 role
  INNER JOIN ROLE_MODEL rm ON role.ROLE_MODEL_ID = rm.ROLE_MODEL_ID
  INNER JOIN LINK_ROLE2_RESOURCE l ON role.ROLE2_ID = l.ROLE2_ID
  INNER JOIN V_PERSONAGE_ROLES2 vpr2 ON role.ROLE2_ID = vpr2.VALUE_ID
WHERE vpr2.PARENT_ID = ? AND l.RESOURCE_ID = ? AND rm.ACTIVE = 1