SELECT
  DISTINCT
  role.ROLE2_ID,
  role.ROLE_MODEL_ID,
  role.NAME
FROM dbo.ROLE2 role
  INNER JOIN LNK_ROLE_PERS_RES_AR l on role.ROLE2_ID = l.ROLE2_ID
WHERE l.PERSONAGE_ID = ? AND l.RESOURCE_ID = ?