;
WITH PLAT AS
(SELECT
   PLATFORM_ID,
   PARENT_ID,
   NAME,
   DISPLAY_NAME,
   DESCRIPTION,
   ROW_NUMBER()
   OVER (
     ORDER BY PLATFORM_ID ) AS ROW_NUM
 FROM dbo.[PLATFORM]
 WHERE IS_DELETED = 0)
SELECT *
FROM PLAT
WHERE ROW_NUM >= ? AND ROW_NUM < ?