SELECT
  DISTINCT
  ar.ACCESS_RIGHT_ID,
  ar.DISPLAY_NAME
FROM
  LNK_ROLE_PERS_RES_AR l
  INNER JOIN
  ACCESS_RIGHT ar
    ON
      l.ACCESS_RIGHT_ID = ar.ACCESS_RIGHT_ID
WHERE
  l.PERSONAGE_ID = ?
  AND l.RESOURCE_ID = ?
  AND l.ROLE2_ID = ?
ORDER BY
  ar.ACCESS_RIGHT_ID
