SELECT
  sp.SECURITY_PRINCIPAL_ID,
  ua.USER_ACCOUNT_ID,
  sp.DISPLAY_NAME,
  sp.UNIT_ID,
  sp.AGENT_ID,
  ua.SYSTEM,
  ua.BEGIN_SYSTEM,
  ua.END_SYSTEM,
  CASE WHEN p.PERSONAGE_ID IS NULL
    THEN 0
  ELSE 1 END AS STATUS
FROM
  USER_ACCOUNT ua
INNER JOIN
  SECURITY_PRINCIPAL sp ON ua.SECURITY_PRINCIPAL_ID = sp.SECURITY_PRINCIPAL_ID
LEFT JOIN
  PERSONAGE p ON p.PERSONAGE_ID = ua.PERSONAGE_ID AND p.IS_DELETED = 0
WHERE
  sp.EXISTENCE = 1 AND
  ua.PERSONAGE_ID = ?
