;
WITH
    AGENT
  AS
  (SELECT
     AGENT_ID,
     PARENT_ID,
     PLATFORM_ID,
     DISPLAY_NAME,
     DESCRIPTION,
     ROW_NUMBER()
     OVER (
       ORDER BY AGENT_ID ) AS ROW_NUM
   FROM dbo.[AGENT]
   WHERE IS_DELETED = 0)
SELECT *
FROM AGENT
WHERE ROW_NUM >= ? AND ROW_NUM < ?