;
WITH
    AG
  AS
  (SELECT
     AGENT_ID,
     PARENT_ID,
     PLATFORM_ID,
     DISPLAY_NAME,
     DESCRIPTION,
     ROW_NUMBER()
     OVER (
       ORDER BY AGENT_ID ) AS ROW_NUM
   FROM [AGENT])
SELECT *
FROM AG
WHERE ROW_NUM >= ? AND ROW_NUM < ?